# docker-compose.yml — à compléter avec les vraies images
version: "3.9"
services:
  preprocessing:
    build: ./services/preprocessing
    ports:
      - "8001:8001"

  inference:
    build: ./services/inference
    ports:
      - "8000:8000"
    depends_on:
      - preprocessing
      - monitoring

  monitoring:
    build: ./services/monitoring
    ports:
      - "8002:8002"
