# ─────────────────────────────────────────────────────────────
# pytest.ini — configuration pytest
# À placer à la RACINE du projet (même niveau que docker-compose.yml)
# ─────────────────────────────────────────────────────────────

[pytest]

# Dossier où pytest cherche les tests
testpaths = tests

# Ajoute les dossiers services au path Python
# Permet aux fichiers de tests d'importer directement
# les modules app.py des services sans conftest.py
pythonpath =
    services/preprocessing
    services/inference

# Affichage verbeux par défaut
addopts = -v